/**
 * Role entity types.
 *
 * The canonical `Role` shape comes from `bindings/Role.ts`
 * (auto-generated by ts-rs from the Rust domain crate). Re-exported
 * here so call-sites import via the FSD entity surface
 * (`@entities/role`) rather than reaching into `bindings/` directly.
 */

export type { Role } from "@bindings/Role";
