/**
 * Prompt entity types.
 *
 * The canonical `Prompt` shape comes from `bindings/Prompt.ts`
 * (auto-generated by ts-rs). Re-exported here so call-sites import via
 * the FSD entity surface (`@entities/prompt`) rather than reaching into
 * `bindings/` directly.
 */

export type { Prompt } from "@bindings/Prompt";
