/**
 * AgentReport entity types.
 *
 * The canonical `AgentReport` shape comes from `bindings/AgentReport.ts`
 * (auto-generated by ts-rs from the Rust domain crate). Re-exported
 * here so call-sites import via the FSD entity surface
 * (`@entities/agent-report`) rather than reaching into `bindings/` directly.
 */

export type { AgentReport } from "@bindings/AgentReport";
