/**
 * McpServer entity types.
 *
 * Canonical shapes come from `bindings/` (auto-generated by ts-rs from
 * the Rust domain crate). Re-exported here so call-sites import via the
 * FSD entity surface (`@entities/mcp-server`) rather than reaching into
 * `bindings/` directly.
 */

export type { McpServer } from "@bindings/McpServer";
export type { McpServerStatus } from "@bindings/McpServerStatus";
export type { McpServerHealthState } from "@bindings/McpServerHealthState";
export type { RefreshReport } from "@bindings/RefreshReport";
export type { Transport } from "@bindings/Transport";
