/**
 * Space entity types.
 *
 * The canonical `Space` shape comes from `bindings/Space.ts`
 * (auto-generated by ts-rs from the Rust domain crate). Round-21 adds a
 * `projectFolderPath` field that the backend has not yet regenerated;
 * we widen the binding here so call-sites can read/write the field
 * today without falling out of the FSD entity surface.
 *
 * The widened field is intentionally OPTIONAL (`?: string | null`)
 * rather than required so existing fixtures (storybook, unit tests)
 * that build `Space` literals stay assignable. Once the binding is
 * regenerated, drop this shim and import the regenerated `Space`
 * directly.
 *
 * TODO(round-21-backend, migration 020): regenerate `bindings/Space.ts`
 * with `projectFolderPath: string | null` and drop this local widen.
 */

import type { Space as GeneratedSpace } from "@bindings/Space";

export type Space = GeneratedSpace & {
  /**
   * Optional absolute path to the project folder this space represents
   * on disk. `null` means "no folder linked"; UI surfaces a "Reveal in
   * Finder" affordance when set. Never piped into prompts.
   */
  projectFolderPath?: string | null;
};
