/**
 * Space entity types.
 *
 * The canonical `Space` shape comes from `bindings/Space.ts`
 * (auto-generated by ts-rs from the Rust domain crate). Re-exported
 * here so call-sites import via the FSD entity surface
 * (`@entities/space`) rather than reaching into `bindings/` directly.
 */

export type { Space } from "@bindings/Space";
