/**
 * Skill entity types.
 *
 * The canonical `Skill` shape comes from `bindings/Skill.ts`
 * (auto-generated by ts-rs from the Rust domain crate). Re-exported
 * here so call-sites import via the FSD entity surface
 * (`@entities/skill`) rather than reaching into `bindings/` directly.
 */

export type { Skill } from "@bindings/Skill";
