/**
 * Board entity types.
 *
 * The canonical `Board` shape comes from `bindings/Board.ts`
 * (auto-generated by ts-rs from the Rust domain crate). We re-export
 * it here so call-sites import via the FSD entity surface
 * (`@entities/board`) rather than reaching into `bindings/` directly —
 * keeps the entity slice the single point of contact with the Rust
 * contract.
 *
 * UI-only types (e.g. `BoardCardVariant` once we add variants) belong
 * here too. None yet at E2.3.
 */

export type { Board } from "@bindings/Board";
