/**
 * Role-note entity types.
 *
 * The canonical `RoleNote` / `RoleNoteAuthor` shapes come from
 * `bindings/RoleNote.ts` and `bindings/RoleNoteAuthor.ts`
 * (auto-generated by ts-rs from the Rust domain crate). Re-exported
 * here so call-sites import via the FSD entity surface
 * (`@entities/role-note`) rather than reaching into `bindings/`
 * directly.
 */

export type { RoleNote } from "@bindings/RoleNote";
export type { RoleNoteAuthor } from "@bindings/RoleNoteAuthor";
