/**
 * Tag entity types.
 *
 * The canonical `Tag` shape comes from `bindings/Tag.ts`
 * (auto-generated by ts-rs from the Rust domain crate). We re-export
 * it here so call-sites import via the FSD entity surface
 * (`@entities/tag`) rather than reaching into `bindings/` directly.
 */

export type { Tag } from "@bindings/Tag";
