/**
 * Connected-client entity types.
 *
 * The canonical shape comes from `bindings/ConnectedClient.ts`
 * (auto-generated by ts-rs). Re-exported here so call-sites import
 * via the FSD entity surface (`@entities/connected-client`).
 */

export type { ConnectedClient } from "@bindings/ConnectedClient";
