import type { ComponentProps, SVGProps } from "react";

/**
 * Shared props for every Pixel*-icon component generated by
 * tools/icons-build.ts.
 *
 * The barrel re-exports each SVG via vite-plugin-svgr, which produces a
 * `React.FC<SVGProps<SVGSVGElement>>`. Because the source SVGs were
 * sanitized to use `fill="currentColor"`, callers can recolor by setting
 * the inline `color` style or via `color` from CSS context.
 *
 * Common usage:
 *   import { PixelCodingAppsWebsitesDatabase } from "@shared/ui/icon";
 *   <PixelCodingAppsWebsitesDatabase width={20} height={20} />
 *   <PixelCodingAppsWebsitesDatabase style={{ color: "var(--color-cta-bg)" }} />
 *
 * The IconProps type is exported from the barrel for callers wanting an
 * untyped pass-through (`(props: IconProps) => <Comp {...props} />`).
 */
export type IconProps = SVGProps<SVGSVGElement> & {
  /** Convenience: equal width + height. Defaults to 20. */
  size?: number | string;
  /** Forwarded to the root <svg> as its `aria-label` or removed if null. */
  title?: string;
};

/** Helper: SVGR-generated component reference shape. */
export type SvgrComponent = React.FunctionComponent<ComponentProps<"svg">>;
