/**
 * Attachment entity types.
 *
 * The canonical `Attachment` shape comes from `bindings/Attachment.ts`
 * (auto-generated by ts-rs from the Rust domain crate). Re-exported
 * here so call-sites import via the FSD entity surface
 * (`@entities/attachment`) rather than reaching into `bindings/` directly.
 */

export type { Attachment } from "@bindings/Attachment";
