-- 005_prompt_icons.sql — add an optional `icon` identifier to prompts.
--
-- The TS layer maps the identifier (e.g. "star", "bolt", "heart") onto a
-- pixel-icon React component sourced from `src/shared/ui/Icon/`. Storing
-- the identifier as a plain TEXT column keeps the backend agnostic to
-- the icon set: rename a sprite on the frontend without a migration.
--
-- Nullable so existing rows keep their "no icon" behaviour. The
-- application layer treats `NULL` and an empty/unknown identifier the
-- same way (no icon rendered).
ALTER TABLE prompts ADD COLUMN icon TEXT NULL;
