-- 018_role_icon.sql — add an optional `icon` identifier to roles.
--
-- Mirrors `005_prompt_icons.sql`, `007_prompt_group_icons.sql`, and
-- `008_space_board_icons_colors.sql` for the `roles` table. The TS
-- layer maps the identifier (e.g. "star", "bolt", "heart") onto a
-- pixel-icon React component sourced from `src/shared/ui/Icon/`.
-- Storing the identifier as a plain TEXT column keeps the backend
-- agnostic to the icon set: rename a sprite on the frontend without a
-- migration.
--
-- Nullable so existing rows keep their "no icon" behaviour. The
-- application layer treats `NULL` and an empty/unknown identifier the
-- same way (no icon rendered). The migration is purely additive —
-- `ADD COLUMN` does not rewrite existing rows, so SQLite handles it
-- without a table rebuild and the operation is O(1) regardless of
-- table size.
ALTER TABLE roles ADD COLUMN icon TEXT;
