/**
 * Boards IPC client.
 *
 * Wraps Tauri `invoke` calls for the `Board` aggregate. Argument shape
 * follows the contract Olga's Rust side accepts: keys are camelCase on
 * the JS side (Tauri auto-converts to snake_case for Rust per the
 * v2.x convention — see https://tauri.app/v2/concept/inter-process-communication/).
 *
 * Errors thrown by the underlying Rust handler arrive here as a JSON-
 * serialised `AppError` (see `bindings/AppError.ts`). We unwrap and
 * re-throw a typed `AppErrorInstance` so call-sites get a discriminated
 * union via `.error.kind` instead of `unknown`.
 *
 * The `Board` and `AppError` types are imported directly from the
 * ts-rs-generated bindings — never hand-edited, regenerated by
 * `cargo test -p catique-domain && cargo test -p catique-api`.
 */

import {
  AppErrorInstance,
  invokeWithAppError,
} from "@shared/api";
import type { Board } from "@bindings/Board";

/**
 * Re-export the shared `AppErrorInstance` so existing
 * `import { AppErrorInstance } from "@entities/board"` callers keep
 * working. New code should import from `@shared/api` directly
 * (audit-#17).
 */
export { AppErrorInstance };

// audit-#17: AppErrorInstance + invokeWithAppError + isAppErrorShape
// + formatAppErrorMessage now live in `src/shared/api/invokeWithAppError.ts`.
// The shared formatter also handles `forbidden` / `badRequest`
// variants (the local copy used to fail exhaustiveness on those).

/**
 * `list_boards` — return every board across all spaces, ordered by
 * `(spaceId, position)` (Rust side guarantees ordering, see
 * `crates/application/src/boards.rs`).
 */
export async function listBoards(): Promise<Board[]> {
  return invokeWithAppError<Board[]>("list_boards");
}

/**
 * `get_board` — fetch a single board by id. Throws AppError `notFound`
 * if the id is unknown.
 */
export async function getBoard(id: string): Promise<Board> {
  return invokeWithAppError<Board>("get_board", { id });
}

/**
 * Args for `createBoard`. Object form rather than positional so the
 * call-site reads naturally and we can extend (e.g. `roleId`) later
 * without breaking callers.
 */
export interface CreateBoardArgs {
  name: string;
  spaceId: string;
  /**
   * Owner role id (`boards.owner_role_id NOT NULL`, ctq-105). When
   * omitted the server defaults to `maintainer-system` per migration
   * 004; explicit caller usually wants to set this.
   */
  ownerRoleId?: string;
  /** Optional description. `undefined` = omit (treated as null on server). */
  description?: string;
  /** Optional CSS hex color (`#RRGGBB`). */
  color?: string;
  /** Optional pixel-icon identifier (matches `@shared/ui/Icon`). */
  icon?: string;
}

/**
 * `create_board` — create a board in the given space. Validation of
 * `name` length and `spaceId` existence happens server-side; surfaced
 * as AppError `validation` / `notFound`.
 */
export async function createBoard(args: CreateBoardArgs): Promise<Board> {
  const payload: Record<string, unknown> = {
    name: args.name,
    spaceId: args.spaceId,
  };
  if (args.ownerRoleId !== undefined) payload.ownerRoleId = args.ownerRoleId;
  if (args.description !== undefined) payload.description = args.description;
  if (args.color !== undefined) payload.color = args.color;
  if (args.icon !== undefined) payload.icon = args.icon;
  return invokeWithAppError<Board>("create_board", payload);
}

/**
 * Args for `updateBoard`. All fields except `id` are optional — only
 * the fields present in the payload are mutated on the server side.
 * Mirrors `UpdateSpaceArgs` shape from `spacesApi`.
 */
export interface UpdateBoardArgs {
  id: string;
  /** Skip = `undefined`. */
  name?: string;
  /** Skip = `undefined`. */
  spaceId?: string;
  /** Skip = `undefined`. */
  position?: number;
  /**
   * `undefined` = leave as-is, `null` = clear, `string` = set.
   * Matches the `Option<Option<String>>` shape on the Rust side.
   */
  description?: string | null;
  /**
   * `undefined` = leave as-is, `null` = clear, `string` = set.
   * Matches Rust's `Option<Option<String>>` shape.
   */
  color?: string | null;
  /**
   * `undefined` = leave as-is, `null` = clear, `string` = set.
   * Matches Rust's `Option<Option<String>>` shape.
   */
  icon?: string | null;
}

/**
 * `update_board` — partial update. Only supplied fields are changed.
 * Throws AppError `notFound` if the id is unknown, `validation` for
 * constraint violations.
 */
export async function updateBoard(args: UpdateBoardArgs): Promise<Board> {
  const payload: Record<string, unknown> = { id: args.id };
  if (args.name !== undefined) payload.name = args.name;
  if (args.spaceId !== undefined) payload.spaceId = args.spaceId;
  if (args.position !== undefined) payload.position = args.position;
  if (args.description !== undefined) payload.description = args.description;
  if (args.color !== undefined) payload.color = args.color;
  if (args.icon !== undefined) payload.icon = args.icon;
  return invokeWithAppError<Board>("update_board", payload);
}

/**
 * `delete_board` — remove a board. Throws AppError `notFound` if the id
 * is unknown, `transactionRolledBack` if downstream invariants block
 * deletion (e.g. the board has linked tasks/columns the schema doesn't
 * cascade).
 */
export async function deleteBoard(id: string): Promise<void> {
  return invokeWithAppError<void>("delete_board", { id });
}

export interface AddBoardPromptArgs {
  boardId: string;
  promptId: string;
  position: number;
}

/**
 * `add_board_prompt` — attach a prompt to a board at the given position.
 * Throws AppError `transactionRolledBack` on FK violation.
 */
export async function addBoardPrompt(args: AddBoardPromptArgs): Promise<void> {
  return invokeWithAppError<void>("add_board_prompt", {
    boardId: args.boardId,
    promptId: args.promptId,
    position: args.position,
  });
}

/**
 * `set_board_prompts` — replace the board's prompt list with `promptIds`
 * in the supplied order. Backed by the ctq-108 bulk handler. Used by the
 * BoardSettings `<MultiSelect>` (audit-#8).
 */
export async function setBoardPrompts(
  boardId: string,
  promptIds: ReadonlyArray<string>,
): Promise<void> {
  return invokeWithAppError<void>("set_board_prompts", {
    boardId,
    promptIds,
  });
}
