/**
 * Boards IPC client.
 *
 * Wraps Tauri `invoke` calls for the `Board` aggregate. Argument shape
 * follows the contract Olga's Rust side accepts: keys are camelCase on
 * the JS side (Tauri auto-converts to snake_case for Rust per the
 * v2.x convention — see https://tauri.app/v2/concept/inter-process-communication/).
 *
 * Errors thrown by the underlying Rust handler arrive here as a JSON-
 * serialised `AppError` (see `bindings/AppError.ts`). We unwrap and
 * re-throw a typed `AppErrorInstance` so call-sites get a discriminated
 * union via `.error.kind` instead of `unknown`.
 *
 * The `Board` and `AppError` types are imported directly from the
 * ts-rs-generated bindings — never hand-edited, regenerated by
 * `cargo test -p catique-domain && cargo test -p catique-api`.
 */

import { invoke } from "@shared/api";
import type { AppError } from "@bindings/AppError";
import type { Board } from "@bindings/Board";

/**
 * Typed error wrapper around the Rust `AppError` enum.
 *
 * Why a class? Promise rejections from Tauri come through as the
 * deserialised JSON object — instanceof-checking that against a class
 * gives us a stable JS-idiomatic catch path (`if (e instanceof
 * AppErrorInstance)`) AND keeps the typed `.error` payload available
 * for discriminated-union narrowing on `.kind`.
 */
export class AppErrorInstance extends Error {
  /** The discriminated-union payload from `bindings/AppError.ts`. */
  public readonly error: AppError;

  public constructor(error: AppError) {
    super(formatAppErrorMessage(error));
    this.name = "AppErrorInstance";
    this.error = error;
    // Required so `instanceof` works after transpilation.
    Object.setPrototypeOf(this, AppErrorInstance.prototype);
  }

  /** Convenience accessor — `error.kind` short-hand. */
  public get kind(): AppError["kind"] {
    return this.error.kind;
  }
}

/** Render an AppError into a human-readable single line. */
function formatAppErrorMessage(error: AppError): string {
  switch (error.kind) {
    case "validation":
      return `Validation failed: ${error.data.field} — ${error.data.reason}`;
    case "transactionRolledBack":
      return `Transaction rolled back: ${error.data.reason}`;
    case "dbBusy":
      return "Database is busy. Please retry.";
    case "lockTimeout":
      return `Lock timeout on resource: ${error.data.resource}`;
    case "internalPanic":
      return `Internal panic in ${error.data.handler}: ${error.data.message}`;
    case "notFound":
      return `${error.data.entity} not found (id: ${error.data.id})`;
    case "conflict":
      return `Conflict on ${error.data.entity}: ${error.data.reason}`;
    case "secretAccessDenied":
      return `Access denied for secret: ${error.data.secretRef}`;
    default: {
      // exhaustiveness check
      const _exhaustive: never = error;
      return `Unknown error: ${JSON.stringify(_exhaustive)}`;
    }
  }
}

/**
 * Heuristic: a Tauri-rejected promise from a handler that returned
 * `Result<_, AppError>` carries the AppError JSON object. Anything else
 * (string, undefined, generic Error) is a transport-level failure.
 *
 * We accept any object with a string `kind` matching one of the known
 * variants — narrowing further requires the structural shape of `data`,
 * which we trust ts-rs to keep in sync via the bindings.
 */
function isAppErrorShape(value: unknown): value is AppError {
  if (typeof value !== "object" || value === null) return false;
  const kind = (value as { kind?: unknown }).kind;
  if (typeof kind !== "string") return false;
  return (
    kind === "validation" ||
    kind === "transactionRolledBack" ||
    kind === "dbBusy" ||
    kind === "lockTimeout" ||
    kind === "internalPanic" ||
    kind === "notFound" ||
    kind === "conflict" ||
    kind === "secretAccessDenied"
  );
}

/**
 * Invoke a Tauri command and remap any AppError-shaped rejection into
 * an `AppErrorInstance`. Non-AppError rejections (e.g. transport
 * failures, malformed responses) are re-thrown as-is — those represent
 * bugs at the FFI boundary and shouldn't be silently widened into the
 * domain-error type.
 */
async function invokeWithAppError<T>(
  command: string,
  args?: Record<string, unknown>,
): Promise<T> {
  try {
    return await invoke<T>(command, args);
  } catch (raw) {
    if (isAppErrorShape(raw)) {
      throw new AppErrorInstance(raw);
    }
    throw raw;
  }
}

/**
 * `list_boards` — return every board across all spaces, ordered by
 * `(spaceId, position)` (Rust side guarantees ordering, see
 * `crates/application/src/boards.rs`).
 */
export async function listBoards(): Promise<Board[]> {
  return invokeWithAppError<Board[]>("list_boards");
}

/**
 * `get_board` — fetch a single board by id. Throws AppError `notFound`
 * if the id is unknown.
 */
export async function getBoard(id: string): Promise<Board> {
  return invokeWithAppError<Board>("get_board", { id });
}

/**
 * Args for `createBoard`. Object form rather than positional so the
 * call-site reads naturally and we can extend (e.g. `roleId`) later
 * without breaking callers.
 */
export interface CreateBoardArgs {
  name: string;
  spaceId: string;
  /** Optional description. `undefined` = omit (treated as null on server). */
  description?: string;
}

/**
 * `create_board` — create a board in the given space. Validation of
 * `name` length and `spaceId` existence happens server-side; surfaced
 * as AppError `validation` / `notFound`.
 */
export async function createBoard(args: CreateBoardArgs): Promise<Board> {
  const payload: Record<string, unknown> = {
    name: args.name,
    spaceId: args.spaceId,
  };
  if (args.description !== undefined) payload.description = args.description;
  return invokeWithAppError<Board>("create_board", payload);
}

/**
 * Args for `updateBoard`. All fields except `id` are optional — only
 * the fields present in the payload are mutated on the server side.
 * Mirrors `UpdateSpaceArgs` shape from `spacesApi`.
 */
export interface UpdateBoardArgs {
  id: string;
  /** Skip = `undefined`. */
  name?: string;
  /** Skip = `undefined`. */
  spaceId?: string;
  /** Skip = `undefined`. */
  position?: number;
  /**
   * `undefined` = leave as-is, `null` = clear, `string` = set.
   * Matches the `Option<Option<String>>` shape on the Rust side.
   */
  description?: string | null;
}

/**
 * `update_board` — partial update. Only supplied fields are changed.
 * Throws AppError `notFound` if the id is unknown, `validation` for
 * constraint violations.
 */
export async function updateBoard(args: UpdateBoardArgs): Promise<Board> {
  const payload: Record<string, unknown> = { id: args.id };
  if (args.name !== undefined) payload.name = args.name;
  if (args.spaceId !== undefined) payload.spaceId = args.spaceId;
  if (args.position !== undefined) payload.position = args.position;
  if (args.description !== undefined) payload.description = args.description;
  return invokeWithAppError<Board>("update_board", payload);
}

/**
 * `delete_board` — remove a board. Throws AppError `notFound` if the id
 * is unknown, `transactionRolledBack` if downstream invariants block
 * deletion (e.g. the board has linked tasks/columns the schema doesn't
 * cascade).
 */
export async function deleteBoard(id: string): Promise<void> {
  return invokeWithAppError<void>("delete_board", { id });
}

export interface AddBoardPromptArgs {
  boardId: string;
  promptId: string;
  position: number;
}

/**
 * `add_board_prompt` — attach a prompt to a board at the given position.
 * Throws AppError `transactionRolledBack` on FK violation.
 */
export async function addBoardPrompt(args: AddBoardPromptArgs): Promise<void> {
  return invokeWithAppError<void>("add_board_prompt", {
    boardId: args.boardId,
    promptId: args.promptId,
    position: args.position,
  });
}
