/**
 * McpTool entity types.
 *
 * The canonical `McpTool` shape comes from `bindings/McpTool.ts`
 * (auto-generated by ts-rs from the Rust domain crate). Re-exported
 * here so call-sites import via the FSD entity surface
 * (`@entities/mcp-tool`) rather than reaching into `bindings/` directly.
 */

export type { McpTool } from "@bindings/McpTool";
