// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ActivityEvent = { 
/**
 * Monotonic sequence id assigned by SQLite. Stable across the
 * lifetime of the row; not reused after purge.
 */
seq: bigint, 
/**
 * `<domain>:<verb>` event name as emitted by the application
 * layer (e.g. `"task:created"`).
 */
name: string, 
/**
 * JSON-serialised payload — the same shape the realtime emit
 * broadcasted on the Tauri channel.
 */
payloadJson: string, 
/**
 * D-D scope discriminator. One of:
 * `"global" | "space" | "board" | "column" | "task" | "role" |
 * "prompt" | "skill" | "mcp_server" | "tag" | "prompt_group"`.
 */
scopeKind: string, 
/**
 * Entity id matching `scope_kind`. `null` for `scope_kind == "global"`.
 */
scopeId: string | null, 
/**
 * Tier-3 compaction counter. `1` for non-compacted rows; higher
 * values mean the row absorbed N back-to-back same-scope edits
 * inside the 5-minute window (D-D §Compaction).
 */
count: bigint, };