// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentReportKind } from "./AgentReportKind";

export type AgentReport = { id: string, taskId: string, kind: AgentReportKind, title: string, content: string, author: string | null, 
/**
 * Human sign-off checkbox: `true` once a person reviewed and
 * approved the report. Default `false` (migration `045`).
 */
approved: boolean, 
/**
 * Optional reviewer note — corrections to make, or context for the
 * approval. `None` when no comment was left.
 */
reviewComment: string | null, createdAt: bigint, updatedAt: bigint, };