// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Board = { id: string, name: string, spaceId: string, roleId: string | null, position: number, description: string | null, createdAt: bigint, updatedAt: bigint, 
/**
 * Owning cat (a row in `roles`). NOT NULL at the schema level.
 */
ownerRoleId: string, };