// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Board = { id: string, name: string, spaceId: string, roleId: string | null, position: number, description: string | null, 
/**
 * Optional `#RRGGBB` colour override. `None` falls back to the
 * frontend's default palette entry for the board.
 */
color: string | null, 
/**
 * Optional pixel-icon identifier. The TS layer maps this string
 * onto a React component from `src/shared/ui/Icon/`. `None` (and
 * any identifier the frontend doesn't recognise) renders no icon.
 */
icon: string | null, 
/**
 * `true` when this board is the auto-created default for its
 * owning space. Default boards cannot be deleted via the IPC; the
 * only way to remove them is to delete the owning space.
 */
isDefault: boolean, createdAt: bigint, updatedAt: bigint, 
/**
 * Owning cat (a row in `roles`). NOT NULL at the schema level.
 */
ownerRoleId: string, };