// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ClientInstructions = { 
/**
 * Kebab-case client id (e.g. `claude-code`).
 */
clientId: string, 
/**
 * Absolute path to the instructions file (may not exist on disk).
 */
filePath: string, 
/**
 * Full text content of the file. Empty string when the file is absent.
 */
content: string, 
/**
 * Unix-millisecond last-modified time. `0` when the file is absent.
 */
modifiedAt: bigint, 
/**
 * `true` when the file existed on disk at read time.
 */
exists: boolean, };