// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Column = { id: string, boardId: string, name: string, position: bigint, roleId: string | null, createdAt: bigint, 
/**
 * `true` when this column is the board's mandatory default
 * (migration `016_default_board_naming_and_constraints.sql`).
 * Cross-board task moves drop tasks here. Cannot be deleted via
 * IPC; the only way to drop a default column is to delete the
 * owning board.
 */
isDefault: boolean, 
/**
 * Optional icon registry name (e.g. `PixelDesignLayer`). `None`
 * falls back to the column's name-heuristic glyph in the UI.
 * Migration `031_columns_icon_color.sql`.
 */
icon: string | null, 
/**
 * Optional CSS color string applied to the column's icon /
 * accent. `None` inherits `--color-text-default`. Migration
 * `031_columns_icon_color.sql`.
 */
color: string | null, };