// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Column = { id: string, boardId: string, name: string, position: bigint, roleId: string | null, createdAt: bigint, };