// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ConnectedClient = { 
/**
 * Stable id — kebab-case, e.g. `claude-code`, `cursor`.
 */
id: string, 
/**
 * Human display name shown in the Settings UI.
 */
displayName: string, 
/**
 * Absolute config directory resolved by the adapter (e.g.
 * `~/.claude` expanded to `/Users/alice/.claude`).
 */
configDir: string, 
/**
 * Signature file the adapter probes to decide `installed`.
 */
signatureFile: string, 
/**
 * `true` when the signature file existed at the last scan.
 */
installed: boolean, 
/**
 * Per-client user toggle. Defaults to `installed` on first scan;
 * survives subsequent rescans (merge logic in
 * `infrastructure::clients::registry`).
 */
enabled: boolean, 
/**
 * Unix-millisecond timestamp of the last registry rescan.
 */
lastSeenAt: bigint, 
/**
 * `true` when this client supports one-way role-file sync from
 * Catique Hub (ctq-69). Populated from
 * `ClientAdapter::supports_role_sync()` at scan time.
 *
 * Clients where this is `false` (Claude Desktop, Qwen CLI v1) show
 * a "не поддерживается" hint in the Settings UI.
 */
supportsRoleSync: boolean, };