// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectionStatus } from "./ConnectionStatus";

export type ConnectedClient = { 
/**
 * Stable provider id (kebab-case, e.g. `claude-code`).
 */
id: string, 
/**
 * Cached human-readable display name at the time of add.
 */
displayName: string, 
/**
 * Latest sync state for THIS provider. The fan-out
 * `SyncStatus` over every connected provider is reported by the
 * `get_sync_status` IPC; this per-row field lets the UI show a
 * red dot on a single provider chip without re-querying.
 */
connectionStatus: ConnectionStatus, 
/**
 * Unix-millisecond timestamp of the most recent successful sync.
 * `0` when no sync has run yet.
 */
lastSyncedAt: bigint, 
/**
 * Last error message captured during sync, when
 * `connection_status == Error`. `None` otherwise.
 */
lastError: string | null, 
/**
 * Wall-clock millis when the row was inserted.
 */
createdAt: bigint, 
/**
 * Wall-clock millis when the row was last updated.
 */
updatedAt: bigint, };