// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ImportOptions = { 
/**
 * `true` → run preflight + simulated INSERTs in a single transaction
 * then ROLLBACK + cleanup `.import-tmp/`. No mutation of the live
 * target DB. Default: `false` (per D-029 #1).
 */
dryRun: boolean, 
/**
 * `true` → if the target DB already has data, back it up to
 * `db.sqlite.<ISO8601>.bak` then proceed. Default: `false` —
 * preflight PF-9 fails fast on a non-empty target.
 */
overwriteExisting: boolean, };