// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PreflightResults } from "./PreflightResults";

export type ImportReport = { 
/**
 * Wall-clock start, epoch ms (UTC).
 */
startedAtMs: bigint, 
/**
 * Wall-clock finish, epoch ms (UTC).
 */
finishedAtMs: bigint, 
/**
 * `finished_at_ms - started_at_ms`. Convenience for the UI.
 */
durationMs: bigint, 
/**
 * Resolved source path (after symlink resolution if any).
 */
sourcePath: string, 
/**
 * Source file size in bytes.
 */
sourceSizeBytes: bigint, 
/**
 * Computed source schema hash.
 */
sourceSchemaHash: string, 
/**
 * Expected source schema hash baked into Catique
 * (`EXPECTED_SOURCE_SCHEMA_HASH`).
 */
targetSchemaHash: string, 
/**
 * `source_schema_hash == target_schema_hash`.
 */
schemaMatch: boolean, 
/**
 * PF-1..PF-10 outcomes.
 */
preflight: PreflightResults, 
/**
 * Rows imported per table. Keyed by table name. Sorted (BTreeMap)
 * so the JSON output is reproducible.
 */
rowsImported: { [key: string]: bigint }, 
/**
 * FTS rows rebuilt. Keys: `"tasks_fts"`, `"agent_reports_fts"`.
 */
ftsRowsRebuilt: { [key: string]: bigint }, 
/**
 * Number of attachment files copied successfully.
 */
attachmentsCopied: bigint, 
/**
 * Total byte volume of copied attachments.
 */
attachmentsTotalBytes: bigint, 
/**
 * `true` if the run was a dry-run (no mutation outside `.import-tmp/`).
 */
dryRun: boolean, 
/**
 * Final committed DB path; `None` for dry-runs and for runs that
 * errored before the atomic rename step.
 */
commitPath: string | null, 
/**
 * Optional human-readable error reason if the import did not
 * complete. `None` on success.
 */
error: string | null, };