// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type McpCallLog = { id: string, serverId: string, toolName: string, startedAt: bigint, 
/**
 * `None` while the call is in flight. Set on completion.
 */
finishedAt: bigint | null, 
/**
 * `None` in flight; `Some(true)` on success; `Some(false)` on any
 * error path (transport, `isError: true`, keychain resolve, …).
 */
success: boolean | null, 
/**
 * Short structured token (`upstream_timeout`, `keychain_missing`,
 * `isError`, …). MUST NOT contain a resolved secret or arbitrary
 * upstream-supplied content.
 */
error: string | null, bytesIn: bigint | null, bytesOut: bigint | null, };