// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpServerHealthState } from "./McpServerHealthState";

export type McpServerStatus = { serverId: string, state: McpServerHealthState, 
/**
 * Max `mcp_tools.last_synced_at` for upstream tools belonging to
 * this server. `None` means "never introspected" (the server row
 * exists but no `tools/list` has ever completed).
 */
lastSyncedAt: bigint | null, 
/**
 * Count of live upstream tools (source = upstream AND
 * last_synced_at IS NOT NULL).
 */
toolCount: bigint, 
/**
 * `started_at` of the most recent `mcp_call_log` row for this
 * server. `None` means "never called".
 */
lastCallStartedAt: bigint | null, 
/**
 * Outcome of that last call. `None` if `last_call_started_at` is
 * `None`; `Some(true)` for success; `Some(false)` for any error
 * path.
 */
lastCallSuccess: boolean | null, };