// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Transport } from "./Transport";

export type McpServer = { id: string, name: string, transport: Transport, 
/**
 * Endpoint URL for `http` / `sse` transports. `None` for `stdio`.
 */
url: string | null, 
/**
 * Subprocess command line for `stdio` transport. `None` for
 * `http` / `sse`.
 */
command: string | null, 
/**
 * Auth-reference JSON (`{"type":"keychain"|"env","key":"..."}`)
 * or `None` if the server requires no authentication. Raw tokens
 * MUST NOT appear here — see module docs.
 */
authJson: string | null, enabled: boolean, createdAt: bigint, updatedAt: bigint, };