// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpToolSource } from "./McpToolSource";

export type McpTool = { id: string, name: string, description: string | null, schemaJson: string, color: string | null, position: number, 
/**
 * FK to `mcp_servers(id)`. `None` for `source = Manual` rows.
 */
serverId: string | null, 
/**
 * Unqualified upstream tool name. `None` for `source = Manual`.
 */
upstreamName: string | null, source: McpToolSource, lastSyncedAt: bigint | null, createdAt: bigint, updatedAt: bigint, };