// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type McpToolGroup = { id: string, name: string, color: string | null, 
/**
 * Optional pixel-icon identifier; the TS layer maps it onto a React
 * component from `src/shared/ui/Icon/`. `None` renders no icon.
 */
icon: string | null, position: bigint, createdAt: bigint, updatedAt: bigint, };