// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpTool } from "./McpTool";
import type { OriginRef } from "./OriginRef";

export type McpToolWithOrigin = { mcpTool: McpTool, origin: OriginRef, overridden: boolean, 
/**
 * Source MCP-tool group when materialised via a group attachment;
 * see [`PromptWithOrigin::via_group`].
 */
viaGroup?: string, };