// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type McpTool = { id: string, name: string, description: string | null, schemaJson: string, color: string | null, position: number, createdAt: bigint, updatedAt: bigint, };