// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OriginRef = { "kind": "direct" } | { "kind": "role", "id": string } | { "kind": "column", "id": string } | { "kind": "board", "id": string } | { "kind": "space", "id": string };