// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PreflightResults = { 
/**
 * PF-1: source DB exists and is readable.
 */
pf1SourceExists: boolean, 
/**
 * PF-2: `PRAGMA integrity_check` returned `ok`.
 */
pf2IntegrityOk: boolean, 
/**
 * PF-3: `PRAGMA quick_check` + FTS smoke counts pass.
 */
pf3QuickCheckOk: boolean, 
/**
 * PF-4: schema hash matches `EXPECTED_SOURCE_SCHEMA_HASH`.
 */
pf4SchemaHashOk: boolean, 
/**
 * PF-5: target data dir is writable (probe write).
 */
pf5TargetWritable: boolean, 
/**
 * PF-6: free disk ≥ 2× source size.
 */
pf6DiskSpaceOk: boolean, 
/**
 * PF-7: lock acquired on source (read-only).
 */
pf7SourceLockOk: boolean, 
/**
 * PF-8: source FK enforcement enabled (`foreign_keys = ON`).
 */
pf8ForeignKeysOn: boolean, 
/**
 * PF-9: target DB empty OR `overwrite_existing = true`.
 */
pf9TargetEmptyOrOverwrite: boolean, 
/**
 * PF-10: attachments folder readable on source side (or absent —
 * some installs have none, that's fine).
 */
pf10AttachmentsReadable: boolean, 
/**
 * Human-readable per-PF detail. Empty string = no extra info.
 * Key names: `"PF-1"`, `"PF-2"`, …, `"PF-10"`.
 */
messages: { [key: string]: string }, };