// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProjectFile = { 
/**
 * Filename relative to the project folder root (e.g. `AGENTS.md`).
 * Always a single path segment — never contains a separator.
 */
name: string, 
/**
 * Current on-disk content. Empty string when the file does not yet
 * exist — a provider-expected name is still listed so the owner can
 * create it from the editor.
 */
content: string, 
/**
 * `true` when the file currently exists on disk.
 */
exists: boolean, 
/**
 * Connected-provider ids that declare this filename as an agent
 * instruction file. Empty for user-created / foreign markdown.
 */
expectedBy: Array<string>, 
/**
 * File mtime in epoch milliseconds, or `0` when the file does not
 * exist.
 */
updatedAt: bigint, };