// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Prompt = { id: string, name: string, content: string, color: string | null, shortDescription: string | null, 
/**
 * Optional pixel-icon identifier. The TS layer maps this string onto
 * a React component from `src/shared/ui/Icon/`. `None` (and any
 * identifier the frontend doesn't recognise) renders no icon.
 */
icon: string | null, 
/**
 * Worked examples illustrating how the prompt should be used. Stored
 * on disk as a JSON-encoded array (`examples_json` TEXT, migration
 * `006_prompt_examples.sql`); the domain layer always exposes a
 * `Vec<String>` — `NULL` and malformed JSON both round-trip to
 * `vec![]`. The field is "list, possibly empty", not nullable, so
 * it is always present in serialised form.
 */
examples: Array<string>, tokenCount: bigint | null, createdAt: bigint, updatedAt: bigint, };