// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PromptTagMapEntry = { 
/**
 * The prompt id.
 */
promptId: string, 
/**
 * All tag ids currently attached to this prompt.
 */
tagIds: Array<string>, };