// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Prompt = { id: string, name: string, content: string, color: string | null, shortDescription: string | null, 
/**
 * Optional pixel-icon identifier. The TS layer maps this string onto
 * a React component from `src/shared/ui/Icon/`. `None` (and any
 * identifier the frontend doesn't recognise) renders no icon.
 */
icon: string | null, tokenCount: bigint | null, createdAt: bigint, updatedAt: bigint, };