// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OriginRef } from "./OriginRef";
import type { Prompt } from "./Prompt";

export type PromptWithOrigin = { prompt: Prompt, origin: OriginRef, };