// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PrompteryDbInfo = { 
/**
 * Absolute resolved path to the discovered DB. Typically
 * `~/.promptery/db.sqlite`, but may resolve a symlink.
 */
path: string, 
/**
 * Size of the DB file (bytes).
 */
sizeBytes: bigint, 
/**
 * SHA-256 of (schema.sql || migrations[sorted]) as defined in D-019.
 * Allows the UI to surface "schema drift detected" before invoking
 * import.
 */
schemaHash: string, 
/**
 * Quick row-count of `tasks` (NULL if the table cannot be read).
 */
tasksCount: bigint | null, 
/**
 * Last-modified epoch ms, taken from filesystem metadata.
 */
lastModifiedMs: bigint, };