// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PromptGroup = { id: string, name: string, color: string | null, position: bigint, createdAt: bigint, updatedAt: bigint, };