// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Transport } from "./Transport";

export type ProxiedServerMeta = { id: string, name: string, transport: Transport, url: string | null, command: string | null, };