// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProxiedServerMeta } from "./ProxiedServerMeta";

export type ProxiedTool = { qualifiedName: string, serverId: string, upstreamName: string, 
/**
 * JSON Schema for the tool args, as the upstream MCP server
 * advertised it. Opaque to us; the Node side passes it through
 * to the external agent verbatim.
 */
inputSchema: Record<string, unknown>, description: string | null, server: ProxiedServerMeta, };