// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RefreshReport = { 
/**
 * Tool names that were not in the previous inventory.
 */
added: bigint, 
/**
 * Tools whose schema_json differs from the previous inventory.
 */
schemaChanged: bigint, 
/**
 * Tools whose schema is identical; `last_synced_at` was bumped.
 */
stillPresent: bigint, 
/**
 * Tools that were in the previous inventory but missing in the
 * fresh `tools/list` — soft-deleted (`last_synced_at` cleared).
 */
softDeleted: bigint, };