// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

import type { RoleNoteAuthor } from "./RoleNoteAuthor";

export type RoleNote = { id: string, roleId: string, sourceTaskId: string | null, body: string, tags: Array<string>, priority: number, pinned: boolean, authoredBy: RoleNoteAuthor, createdAt: bigint, updatedAt: bigint, };
