// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RoleSyncReport = { 
/**
 * Id of the connected client that was synced.
 */
clientId: string, 
/**
 * Role ids whose files were newly created (did not exist before sync).
 */
created: Array<string>, 
/**
 * Role ids whose files were overwritten (existed with managed marker).
 */
updated: Array<string>, 
/**
 * Role ids whose files were removed (role deleted from Catique Hub).
 */
deleted: Array<string>, 
/**
 * Filenames of user-authored files that were deliberately left
 * untouched (no `catique-` prefix or no managed frontmatter).
 */
skipped: Array<string>, };