// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Role = { id: string, name: string, content: string, color: string | null, 
/**
 * Optional pixel-icon identifier (migration `018_role_icon.sql`).
 * The TS layer maps this string onto a React component from
 * `src/shared/ui/Icon/`. `None` (and any identifier the frontend
 * does not recognise) renders no icon. Mirrors the
 * `Prompt` / `Skill` / `McpTool` / `Space` / `Board` shape.
 */
icon: string | null, createdAt: bigint, updatedAt: bigint, 
/**
 * `true` for application-owned rows (Maintainer, Dirizher). UI
 * hides edit / delete affordances; use-case layer rejects mutation.
 */
isSystem: boolean, };