// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Role = { id: string, name: string, content: string, color: string | null, createdAt: bigint, updatedAt: bigint, 
/**
 * `true` for application-owned rows (Maintainer, Dirizher). UI
 * hides edit / delete affordances; use-case layer rejects mutation.
 */
isSystem: boolean, };