// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RoleContentVersionView = { id: string, roleId: string, content: string, createdAt: bigint, authorNote: string | null, };