// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SearchResult = { "type": "task", id: string, boardId: string, columnId: string, title: string, snippet: string, } | { "type": "agentReport", id: string, taskId: string, title: string, kind: string, snippet: string, };