// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SkillAttachmentKind } from "./SkillAttachmentKind";

export type SkillAttachment = { id: string, skillId: string, kind: SkillAttachmentKind, filename: string | null, mimeType: string | null, sizeBytes: bigint | null, storagePath: string | null, gitUrl: string | null, gitRef: string | null, gitPath: string | null, createdAt: bigint, };