// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SkillStep = { id: string, skillId: string, position: number, title: string, body: string, expectedOutcome: string | null, createdAt: bigint, updatedAt: bigint, };