// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
//
// NOTE: Stub committed alongside SKILL-S12 frontend work; SKILL-S10 (paired
// backend commit) will replace this file verbatim via the ts-rs generator.
// Field shape mirrors the contract specified in the SKILL-S12 brief.

import type { SkillAttachmentKind } from "./SkillAttachmentKind";

export type SkillAttachment = {
  id: string,
  skillId: string,
  kind: SkillAttachmentKind,
  filename: string | null,
  mimeType: string | null,
  sizeBytes: bigint | null,
  storagePath: string | null,
  gitUrl: string | null,
  gitRef: string | null,
  gitPath: string | null,
  createdAt: bigint,
};
