// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Space = { id: string, name: string, prefix: string, description: string | null, isDefault: boolean, position: number, createdAt: bigint, updatedAt: bigint, };