// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SupportedProvider = { 
/**
 * Stable kebab-case id (e.g. `claude-code`).
 */
id: string, 
/**
 * Human-readable display name.
 */
displayName: string, 
/**
 * `true` when the provider supports managed agent files.
 */
supportsAgentFiles: boolean, 
/**
 * `true` when the provider supports a managed MCP server entry.
 */
supportsMcp: boolean, };