// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SyncedRoleFile = { 
/**
 * Id of the connected client (e.g. `"claude-code"`, `"cursor"`).
 */
clientId: string, 
/**
 * The Catique Hub role id this file was generated from.
 */
roleId: string, 
/**
 * Absolute path of the written agent-definition file.
 */
filePath: string, 
/**
 * Unix-millisecond timestamp recorded in the file's frontmatter and
 * returned here for display purposes.
 */
syncedAt: bigint, };