// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SyncState } from "./SyncState";

export type SyncStatus = { state: SyncState, 
/**
 * Provider ids whose most recent sync failed. Empty when
 * `state != Error`.
 */
failingProviders: Array<string>, };