// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Task = { id: string, boardId: string, columnId: string, slug: string, title: string, description: string | null, position: number, roleId: string | null, createdAt: bigint, updatedAt: bigint, 
/**
 * Append-only newline-separated log of timestamped step summaries
 * (`[YYYY-MM-DDTHH:MM:SSZ] {summary}\n`). Default `""`.
 */
stepLog: string, };