// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskKind } from "./TaskKind";

export type Task = { id: string, boardId: string, columnId: string, slug: string, title: string, description: string | null, 
/**
 * Classification of the card. Defaults to [`TaskKind::Blank`] for
 * rows that predate the `kind` column (migration `044`).
 */
kind: TaskKind, position: number, roleId: string | null, createdAt: bigint, updatedAt: bigint, 
/**
 * Append-only newline-separated log of timestamped step summaries
 * (`[YYYY-MM-DDTHH:MM:SSZ] {summary}\n`). Default `""`.
 */
stepLog: string, 
/**
 * Denormalised effective-context counters (refactor-v3 D-B). The
 * kanban card surface reads these directly so a 50-card board open
 * stays one SELECT instead of `N × resolve_task_bundle`. Maintained
 * by application-layer hooks at every mutation that touches
 * `task_prompts` / `task_skills` / `task_mcp_tools` or any
 * `task_*_overrides_v2` row.
 *
 * Formula per kind: `COUNT(task_<kind>) - COUNT(suppress-only
 * overrides for <kind>)`. Replace-overrides preserve cardinality
 * (one row in, one row out) so they do not enter the formula. See
 * `docs/refactor-v3/decisions/D-B-effective-counter-denormalization.md`.
 *
 * `#[serde(default)]` keeps the wire shape forward-compatible: a
 * persisted JSON payload predating D-B can still deserialise into
 * the new struct (missing fields fall through to `0`).
 */
effectivePromptCount: bigint, effectiveSkillCount: bigint, effectiveToolCount: bigint, };