// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PromptWithOrigin } from "./PromptWithOrigin";
import type { Role } from "./Role";
import type { Task } from "./Task";

export type TaskBundle = { task: Task, 
/**
 * Active role for this task: `task.role_id` if set, else
 * `column.role_id`, else `board.role_id`. Resolved at read time so
 * the consumer never has to walk the chain itself.
 */
role: Role | null, 
/**
 * Prompts ordered by precedence-then-position. Direct rows lead;
 * inherited rows follow in `Role > Column > Board > Space` order.
 */
prompts: Array<PromptWithOrigin>, };