// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskTemplateKind } from "./TaskTemplateKind";

export type TaskTemplate = { id: string, name: string, kind: TaskTemplateKind, 
/**
 * Short helper shown next to the template in the picker.
 */
description: string, 
/**
 * Markdown skeleton inserted into the new task's description.
 */
body: string, icon: string | null, color: string | null, position: number, createdAt: bigint, updatedAt: bigint, };