// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskLinkKind } from "./TaskLinkKind";

export type TaskLink = { srcTaskId: string, dstTaskId: string, kind: TaskLinkKind, createdAt: bigint, };