// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpTool } from "./McpTool";
import type { McpToolWithOrigin } from "./McpToolWithOrigin";
import type { Prompt } from "./Prompt";
import type { PromptWithOrigin } from "./PromptWithOrigin";
import type { Role } from "./Role";
import type { Skill } from "./Skill";
import type { SkillWithOrigin } from "./SkillWithOrigin";
import type { Task } from "./Task";

export type TaskBundle = { task: Task, 
/**
 * Active role for this task: `task.role_id` if set, else
 * `column.role_id`, else `board.role_id`. Resolved at read time so
 * the consumer never has to walk the chain itself.
 */
role: Role | null, 
/**
 * Prompts ordered by precedence-then-position. Direct rows lead;
 * inherited rows follow in `Role > Column > Board > Space` order.
 */
prompts: Array<PromptWithOrigin>, 
/**
 * Skills ordered by the same precedence rule as `prompts`.
 * Defaults to an empty vec for backward compatibility with
 * pre-ctq-119 callers (the `serde(default)` keeps deserialisation
 * of stored payloads forward-compatible).
 */
skills: Array<SkillWithOrigin>, 
/**
 * MCP tools ordered by the same precedence rule.
 */
mcpTools: Array<McpToolWithOrigin>, 
/**
 * Inherited prompts the user explicitly suppressed via
 * `task_prompt_overrides_v2` (refactor-v3 D-A). The UI renders
 * these struck-through with a "restore" affordance. Empty on
 * pre-D-A tasks. `serde(default)` keeps backward compatibility.
 */
suppressedPrompts: Array<Prompt>, 
/**
 * Inherited skills the user explicitly suppressed.
 */
suppressedSkills: Array<Skill>, 
/**
 * Inherited mcp_tools the user explicitly suppressed.
 */
suppressedMcpTools: Array<McpTool>, };