// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TaskRating = { taskId: string, 
/**
 * `Some(-1 | 0 | +1)` for an explicit rating. `None` means
 * "row exists but rating is cleared" — a state the upsert layer
 * produces when the user un-rates a task.
 */
rating: number | null, 
/**
 * Wall-clock unix-ms of the most recent set / clear call (UPSERT).
 */
ratedAt: bigint, };