// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpToolWithOrigin } from "./McpToolWithOrigin";
import type { PromptWithOrigin } from "./PromptWithOrigin";
import type { Role } from "./Role";
import type { SkillWithOrigin } from "./SkillWithOrigin";
import type { Task } from "./Task";

export type TaskBundle = { task: Task, 
/**
 * Active role for this task: `task.role_id` if set, else
 * `column.role_id`, else `board.role_id`. Resolved at read time so
 * the consumer never has to walk the chain itself.
 */
role: Role | null, 
/**
 * Prompts ordered by precedence-then-position. Direct rows lead;
 * inherited rows follow in `Role > Column > Board > Space` order.
 */
prompts: Array<PromptWithOrigin>, 
/**
 * Skills ordered by the same precedence rule as `prompts`.
 * Defaults to an empty vec for backward compatibility with
 * pre-ctq-119 callers (the `serde(default)` keeps deserialisation
 * of stored payloads forward-compatible).
 */
skills: Array<SkillWithOrigin>, 
/**
 * MCP tools ordered by the same precedence rule.
 */
mcpTools: Array<McpToolWithOrigin>, };