// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TaskMatch = { 
/**
 * Stable task id.
 */
id: string, 
/**
 * Title verbatim from `tasks.title`.
 */
title: string, 
/**
 * `tasks.description` — `None` for tasks with NULL description.
 */
description: string | null, 
/**
 * Owning cat id (the schema's `tasks.role_id`). `None` when the
 * task does not have a cat assigned at the task level — the
 * search-time JOIN does not chase the column/board fallback.
 */
roleId: string | null, 
/**
 * FTS5 `snippet()` fragment over the `title` column with HTML
 * highlighting (`<b>…</b>`).
 */
snippet: string, };