/**
 * icons-build.ts
 *
 * One-shot script that:
 *  1. Walks the source SVG directory ($SVG_SRC, default: ~/Desktop/svg)
 *  2. Filters to 32×32 viewBox icons (skips wordmark/banner SVGs)
 *  3. Strips fixed fills ("#000001", "#121212", "black") → currentColor,
 *     so consumers can recolor with `color` / `style.color` props.
 *  4. Renames each file to PascalCase with `Pixel` prefix
 *     (e.g. `coding-apps-websites-database--Streamline-Pixel.svg`
 *      →    `PixelCodingAppsWebsitesDatabase.svg`)
 *  5. Writes the cleaned file into src/shared/ui/icon/svg/
 *  6. Generates src/shared/ui/icon/index.ts — a barrel exporting every
 *     icon as a named React component via vite-plugin-svgr.
 *
 * Run:  pnpm icons:build
 */
import { existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync, rmSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const PROJECT_ROOT = resolve(__dirname, "..");
const TARGET_DIR = join(PROJECT_ROOT, "src/shared/ui/icon/svg");
const BARREL_PATH = join(PROJECT_ROOT, "src/shared/ui/icon/index.ts");
const SOURCE_DIR = process.env.SVG_SRC ?? join(homedir(), "Desktop/svg");

function walk(dir: string, out: string[] = []): string[] {
  for (const entry of readdirSync(dir)) {
    // Finder duplicate copies (`name 2.svg`) — skip; we already pick up the
    // original file in the same scan and the duplicates are byte-identical.
    if (/ \d+\.svg$/.test(entry)) continue;
    const full = join(dir, entry);
    const stat = statSync(full);
    if (stat.isDirectory()) walk(full, out);
    else if (entry.endsWith(".svg")) out.push(full);
  }
  return out;
}

/**
 * `building-real-eastate-house-1--Streamline-Pixel.svg` →
 * `PixelBuildingRealEstateHouse1`
 *
 * Steps:
 *   strip extension
 *   drop trailing `--Streamline-Pixel`
 *   normalize separators (`-`, `_`, ` `) → space
 *   PascalCase each token
 *   prefix with `Pixel`
 *   typo-fix: `eastate` → `estate`
 */
function toComponentName(filename: string): string {
  let base = filename.replace(/\.svg$/i, "");
  base = base.replace(/--?streamline-pixel$/i, "").replace(/-streamline-pixel$/i, "");
  base = base
    .replace(/eastate/gi, "estate")
    .replace(/cosmatic/gi, "cosmetic")
    .replace(/documant/gi, "document")
    .replace(/grahp/gi, "graph")
    .replace(/prodect/gi, "product")
    .replace(/conctruction/gi, "construction")
    .replace(/constuction/gi, "construction");
  // Pad numbers next to letters so the case logic preserves them
  // (e.g. `house-1` already separated by dash — fine).
  const tokens = base.split(/[-_\s]+/).filter(Boolean);
  const pascal = tokens
    .map((t) => t.charAt(0).toUpperCase() + t.slice(1).toLowerCase())
    .join("");
  return `Pixel${pascal}`;
}

function isThirtyTwo(svg: string): boolean {
  const m = svg.match(/viewBox="0\s+0\s+(\d+)\s+(\d+)"/);
  if (!m) return false;
  return m[1] === "32" && m[2] === "32";
}

function sanitize(svg: string): string {
  return svg
    .replace(/fill="#000001"/gi, 'fill="currentColor"')
    .replace(/fill="#121212"/gi, 'fill="currentColor"')
    .replace(/fill="black"/gi, 'fill="currentColor"')
    .replace(/fill="#000000"/gi, 'fill="currentColor"')
    .replace(/fill="#000"/gi, 'fill="currentColor"');
}

function main(): void {
  if (!existsSync(SOURCE_DIR)) {
    console.error(`[icons-build] source dir not found: ${SOURCE_DIR}`);
    process.exit(1);
  }

  // Wipe target so removed source icons don't linger
  if (existsSync(TARGET_DIR)) rmSync(TARGET_DIR, { recursive: true, force: true });
  mkdirSync(TARGET_DIR, { recursive: true });

  const files = walk(SOURCE_DIR);
  const seen = new Map<string, string>(); // componentName → outFilename
  let kept = 0;
  let skippedNon32 = 0;
  let skippedDup = 0;

  for (const path of files) {
    const filename = path.split("/").pop() ?? "";
    const raw = readFileSync(path, "utf8");
    if (!isThirtyTwo(raw)) {
      skippedNon32++;
      continue;
    }
    const compName = toComponentName(filename);
    if (seen.has(compName)) {
      skippedDup++;
      continue;
    }
    const outFilename = `${compName}.svg`;
    writeFileSync(join(TARGET_DIR, outFilename), sanitize(raw));
    seen.set(compName, outFilename);
    kept++;
  }

  // Barrel: alphabetical export list with `Pixel` prefix
  const exportNames = [...seen.keys()].sort();
  const lines: string[] = [
    "/* AUTO-GENERATED by tools/icons-build.ts — do not edit by hand. */",
    "/* eslint-disable */",
    "",
  ];
  for (const name of exportNames) {
    lines.push(`export { default as ${name} } from "./svg/${name}.svg?react";`);
  }
  lines.push("");
  lines.push("export type { IconProps } from \"./IconProps\";");
  lines.push("");
  writeFileSync(BARREL_PATH, lines.join("\n"));

  console.log(`[icons-build] wrote ${kept} icons → ${TARGET_DIR}`);
  console.log(`[icons-build] skipped: ${skippedNon32} non-32×32, ${skippedDup} duplicates`);
  console.log(`[icons-build] barrel: ${BARREL_PATH} (${exportNames.length} exports)`);
}

main();
