/*
 * tokens-build.ts — emit src/app/styles/tokens.generated.css from
 * design-tokens/tokens.json.
 *
 * Two-tier model: primitive (color, space, radius) + semantic (light, dark).
 * Semantic values may be reference strings of the form "{primitive.color.gold-500}".
 *
 * Run: pnpm tokens:build
 *
 * Deterministic — output ordering is governed by the JSON key order
 * (Node preserves insertion order on parse), so checking in the result is safe.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, "..");
const SRC = resolve(ROOT, "design-tokens/tokens.json");
const DST = resolve(ROOT, "src/app/styles/tokens.generated.css");

interface PrimitiveBlock {
  [group: string]: { [name: string]: string };
}
interface SemanticBlock {
  [name: string]: string;
}
interface TokensFile {
  primitive: PrimitiveBlock;
  semantic: { light: SemanticBlock; dark: SemanticBlock };
}

const REF = /^\{primitive\.([a-z]+)\.([a-zA-Z0-9_-]+)\}$/;

function resolveRef(value: string, primitive: PrimitiveBlock): string {
  const match = REF.exec(value);
  if (!match) return value;
  const [, group, name] = match;
  if (group === undefined || name === undefined) return value;
  const groupObj = primitive[group];
  if (!groupObj) {
    throw new Error(`tokens-build: primitive group "${group}" not found in tokens.json`);
  }
  const literal = groupObj[name];
  if (literal === undefined) {
    throw new Error(`tokens-build: primitive ${group}.${name} not found`);
  }
  return literal;
}

function emit(): string {
  const raw = readFileSync(SRC, "utf8");
  const tokens = JSON.parse(raw) as TokensFile;

  const lines: string[] = [];
  lines.push("/*");
  lines.push(" * AUTO-GENERATED by tools/tokens-build.ts — DO NOT EDIT BY HAND.");
  lines.push(" * Source: design-tokens/tokens.json");
  lines.push(" * Run `pnpm tokens:build` to regenerate.");
  lines.push(" */");
  lines.push("");
  lines.push(":root {");
  lines.push("  /* Primitive layer — physical values, theme-independent. */");
  for (const [group, entries] of Object.entries(tokens.primitive)) {
    lines.push(`  /* ${group} */`);
    for (const [name, value] of Object.entries(entries)) {
      lines.push(`  --${group}-${name}: ${value};`);
    }
  }
  lines.push("");
  lines.push("  /* Semantic layer — light theme (default). UI reads only these. */");
  for (const [name, value] of Object.entries(tokens.semantic.light)) {
    const resolved = resolveRef(value, tokens.primitive);
    if (resolved.startsWith("#") || resolved.startsWith("rgb") || resolved.startsWith("hsl") || resolved.match(/^[0-9 .]+px/) || resolved.startsWith("0 ")) {
      // literal — emit as-is
      lines.push(`  --${name}: ${resolved};`);
    } else if (REF.test(value)) {
      // reference resolved to literal but in case of deeper chains:
      lines.push(`  --${name}: ${resolved};`);
    } else {
      lines.push(`  --${name}: ${value};`);
    }
  }
  lines.push("}");
  lines.push("");
  lines.push("/* Semantic layer — dark theme override, activated by [data-theme=\"dark\"]. */");
  lines.push('[data-theme="dark"] {');
  for (const [name, value] of Object.entries(tokens.semantic.dark)) {
    const resolved = resolveRef(value, tokens.primitive);
    lines.push(`  --${name}: ${resolved};`);
  }
  lines.push("}");
  lines.push("");

  return lines.join("\n");
}

const output = emit();
writeFileSync(DST, output, "utf8");

// eslint-disable-next-line no-console
console.log(`tokens-build: wrote ${DST}`);
