/**
 * PromptGroup entity types.
 *
 * The canonical `PromptGroup` shape comes from `bindings/PromptGroup.ts`
 * (auto-generated by ts-rs from the Rust domain crate). Re-exported
 * here so call-sites import via the FSD entity surface
 * (`@entities/prompt-group`) rather than reaching into `bindings/` directly.
 */

export type { PromptGroup } from "@bindings/PromptGroup";
